#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'src/scss/**/*.scss'
# Rule Configuration
rules:
  bem-depth: 1
  border-zero:
    - 1
    -
      convention: none

  class-name-format: 
    - 2
    - 
      convention: hyphenatedbem
      allow-leading-underscore: true
      convention-explanation: '^(?:u|is|has)\-[a-z][a-zA-Z0-9]*$|^(?!u|is|has)[a-zA-Z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$'

  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 0
  no-duplicate-properties: 0
  empty-line-between-blocks:
    - 1
    - 
      include: true
      allow-single-line-rulesets: true

  no-empty-rulesets: 0
  final-newline:
    - 2
    -
      include: true

  hex-length:
    - 1
    -
      style: short

  no-invalid-hex: 2
  clean-import-paths:
    - 2
    - 
      leading-underscore: false
      filename-extension: false

  leading-zero:
    - 2
    -
      include: true
  
  no-mergeable-selectors: 0
  nesting-depth: 
    - 2
    - 
      max-depth: 3

  no-misspelled-properties: 0
  property-units: 0
  pseudo-element: 2
  no-qualifying-elements:
    - 2
    - 
      allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false

  shorthand-values:
    - 2
    -
      allowed-shorthands:
        - 1
        - 2

  single-line-per-selector: 2
  space-after-comma:
    - 2
    -
      include: true

  space-after-colon:
    - 2
    -
      include: true
  
  space-around-operator:
    - 2
    -
      include: true

  space-before-brace:
    - 2
    -
      include: true

  space-between-parens:
    - 2
    -
      include: false

  quotes:
    - 2
    -
      style: single

  trailing-semicolon:
    - 2
    -
      include: true

  no-trailing-zero: 2
  no-transition-all: 0
  url-quotes: 2
  zero-unit:
    - 2
    -
      include: false

  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 1
    -
      style: lowercase

  indentation:
    - 1
    -
      size: 2

  property-sort-order:
    - 2
    -
      order: 'concentric'

  variable-for-property: 0